### ISSUE TITLE
Update to Nautilus 3

### ISSUE THREAD

**Issue by nerdoc** [tapio/nautilus-git-scripts#4]
Do you have plants to update these (useful) scripts to N3? Do you accept Pull requests?

**Comment by tapio** [comment]
What does not work? #3 should have updated the scripts location to a modern one.

PRs are welcome.

**Comment by nerdoc** [comment]
It somehow "works" in Nautilus 3, as it loads the plugin and shows the scrips in the (some) menu. But:
e.g. in git.conf, I saw the line

    ZENITY_WINDOW_ICON="$HOME/.gnome2/nautilus-scripts/Git/git.png"

But the icon is not shown anywhere. Even if I change it to

    ZENITY_WINDOW_ICON="$HOME/.local/share/nautilus/scripts/Git/git.png"

It does not show any icon. where is this supposed to show up?

There are some other glitches, and I don't know the internals of the nautilus plugin system, but I like the extension very much (and more would like to use it on a daily basis ;-) ) so If you don't mind I would add these glitches issue per issue. PR as well, but don't expect high quality code as I know python and bash, but no nautilus internals...

**Comment by nerdoc** [comment]
IMHO we could close this issue (doing that, as the author). It is kind of invalid as it _works_ on GNOME 3 Should I file another issue for the icon?
